sonar.projectKey=SmartLogix
sonar.projectName=SmartLogix
sonar.projectVersion=1.0

sonar.sources=bff-service/src,inventory-service/src,orders-service/src,payment-service/src,shipping-service/src,frontend/src
sonar.tests=inventory-service/src/__tests__,orders-service/src/__tests__,payment-service/src/__tests__
sonar.test.inclusions=**/__tests__/**/*.js
sonar.javascript.lcov.reportPaths=inventory-service/coverage/lcov.info,orders-service/coverage/lcov.info,payment-service/coverage/lcov.info

sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
