events {
  worker_connections 1024;
}

http {
  log_format main '$remote_addr - $request_time s - $status - "$request"';
  access_log /var/log/nginx/access.log main;
  error_log  /var/log/nginx/error.log warn;

  limit_req_zone $binary_remote_addr zone=api:10m rate=30r/s;

  # Usar el resolver interno de Docker para nombres de contenedores
  resolver 127.0.0.11 valid=10s ipv6=off;

  server {
    listen 80;
    server_name localhost;

    add_header Access-Control-Allow-Origin  "*" always;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;

    if ($request_method = OPTIONS) {
      return 204;
    }

    location = /health {
      return 200 '{"status":"ok","service":"api-gateway"}';
      add_header Content-Type application/json;
    }

    # Todas las rutas /api/ van al BFF
    location /api/ {
      limit_req zone=api burst=20 nodelay;
      set $bff_upstream http://bff-service:4000;
      proxy_pass         $bff_upstream;
      proxy_set_header   Host              $host;
      proxy_set_header   X-Real-IP         $remote_addr;
      proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Proto $scheme;
      proxy_read_timeout 30s;
      proxy_connect_timeout 5s;
      add_header Cache-Control "no-store, no-cache" always;
    }

    # El frontend React
    location / {
      set $fe_upstream http://frontend:3000;
      proxy_pass $fe_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
